# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/analyze.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/analyze.proto\x12\x07\x61nalyze\"0\n\nrpcComment\x12\x0f\n\x07\x43ontent\x18\x01 \x03(\t\x12\x11\n\tproductId\x18\x02 \x01(\t\"4\n\x0e\x41nalyzeComment\x12\x10\n\x08\x46raction\x18\x01 \x01(\x05\x12\x10\n\x08Interval\x18\x02 \x03(\x05\x32R\n\x07Greeter\x12G\n\x15\x41nalysisCommentsByNLP\x12\x13.analyze.rpcComment\x1a\x17.analyze.AnalyzeComment\"\x00\x42\x16Z\x14goGRPC/AnalysisByNLPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.analyze_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024goGRPC/AnalysisByNLP'
  _RPCCOMMENT._serialized_start=32
  _RPCCOMMENT._serialized_end=80
  _ANALYZECOMMENT._serialized_start=82
  _ANALYZECOMMENT._serialized_end=134
  _GREETER._serialized_start=136
  _GREETER._serialized_end=218
# @@protoc_insertion_point(module_scope)
