# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wordCloud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwordCloud.proto\x12\tmyservice\"\x1d\n\nrpcComment\x12\x0f\n\x07\x43ontent\x18\x01 \x03(\t\"\"\n\x0crpcWordCloud\x12\x12\n\nwordsCloud\x18\x01 \x01(\t2P\n\x07Greeter\x12\x45\n\x11WordCloudAnalysis\x12\x15.myservice.rpcComment\x1a\x17.myservice.rpcWordCloud\"\x00\x42\x13Z\x11goGRPC/WordsCloudb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wordCloud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021goGRPC/WordsCloud'
  _RPCCOMMENT._serialized_start=30
  _RPCCOMMENT._serialized_end=59
  _RPCWORDCLOUD._serialized_start=61
  _RPCWORDCLOUD._serialized_end=95
  _GREETER._serialized_start=97
  _GREETER._serialized_end=177
# @@protoc_insertion_point(module_scope)
