# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service.wordCloud_pb2 as wordCloud__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WordCloudAnalysis = channel.unary_unary(
                '/myservice.Greeter/WordCloudAnalysis',
                request_serializer=wordCloud__pb2.rpcComment.SerializeToString,
                response_deserializer=wordCloud__pb2.rpcWordCloud.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WordCloudAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WordCloudAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.WordCloudAnalysis,
                    request_deserializer=wordCloud__pb2.rpcComment.FromString,
                    response_serializer=wordCloud__pb2.rpcWordCloud.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservice.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WordCloudAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.Greeter/WordCloudAnalysis',
            wordCloud__pb2.rpcComment.SerializeToString,
            wordCloud__pb2.rpcWordCloud.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
